# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Product.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem, QMessageBox


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1011, 456)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(570, 50, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 200, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 240, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 280, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(40, 320, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(40, 360, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(570, 80, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(570, 100, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.edtId = QtWidgets.QLineEdit(Form)
        self.edtId.setGeometry(QtCore.QRect(130, 160, 301, 22))
        self.edtId.setObjectName("edtId")
        self.edtBarkode = QtWidgets.QLineEdit(Form)
        self.edtBarkode.setGeometry(QtCore.QRect(130, 200, 301, 22))
        self.edtBarkode.setObjectName("edtBarkode")
        self.edtName = QtWidgets.QLineEdit(Form)
        self.edtName.setGeometry(QtCore.QRect(130, 240, 301, 22))
        self.edtName.setObjectName("edtName")
        self.edtKategori = QtWidgets.QLineEdit(Form)
        self.edtKategori.setGeometry(QtCore.QRect(130, 280, 301, 22))
        self.edtKategori.setObjectName("edtKategori")
        self.edtQty = QtWidgets.QLineEdit(Form)
        self.edtQty.setGeometry(QtCore.QRect(130, 320, 301, 22))
        self.edtQty.setObjectName("edtQty")
        self.edtHarga = QtWidgets.QLineEdit(Form)
        self.edtHarga.setGeometry(QtCore.QRect(130, 350, 301, 22))
        self.edtHarga.setObjectName("edtHarga")
        self.tSimpan = QtWidgets.QPushButton(Form)
        self.tSimpan.setGeometry(QtCore.QRect(140, 390, 93, 28))
        self.tSimpan.setObjectName("tSimpan")
        self.tUbah = QtWidgets.QPushButton(Form)
        self.tUbah.setGeometry(QtCore.QRect(240, 390, 93, 28))
        self.tUbah.setObjectName("tUbah")
        self.tHapus = QtWidgets.QPushButton(Form)
        self.tHapus.setGeometry(QtCore.QRect(340, 390, 93, 28))
        self.tHapus.setObjectName("tHapus")
        self.tCari = QtWidgets.QPushButton(Form)
        self.tCari.setGeometry(QtCore.QRect(890, 390, 93, 28))
        self.tCari.setObjectName("tCari")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(460, 160, 521, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.edtCari = QtWidgets.QLineEdit(Form)
        self.edtCari.setGeometry(QtCore.QRect(460, 390, 411, 22))
        self.edtCari.setObjectName("edtCari")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(100, 70, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")

        self.tSimpan.clicked.connect(self.simpandata)
        self.tUbah.clicked.connect(self.ubahproduct)
        self.tHapus.clicked.connect(self.hapusproduct)
        self.tCari.clicked.connect(self.cariproduct)
        self.loadproduct()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def simpandata(self):
        try:
            Id = self.edtId.text()
            barkode = self.edtBarkode.text()
            name = self.edtName.text()
            kategori = self.edtKategori.text()
            qty = self.edtQty.text()
            harga = self.edtHarga.text()

            if not all([Id, barkode, name, kategori, qty, harga]):
                QMessageBox.warning(None, "Error", "Pastikan semua field diisi!")
                return

            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_penjualan"
            )
            cursor = mydb.cursor()
            sql = "INSERT INTO product (Id, barkode, name, kategori, qty, harga) VALUES (%s, %s, %s, %s, %s, %s)"
            val = (Id, barkode, name, kategori, qty, harga)
            cursor.execute(sql, val)
            mydb.commit()
            self.loadproduct()
            self.edtId.clear()
            self.edtBarkode.clear()
            self.edtName.clear()
            self.edtKategori.clear()
            self.edtQty.clear()
            self.edtHarga.clear()
        except mc.Error as e:
            QMessageBox.critical(None, "Error", f"Database error: {str(e)}")

    def loadproduct(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_penjualan"
            )
            cursor = mydb.cursor()
            cursor.execute("SELECT * FROM product ORDER BY Id ASC")
            result = cursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
        except mc.Error as e:
            QMessageBox.critical(None, "Error", f"Database error: {str(e)}")

    def ubahproduct(self):
        try:
            Id = self.edtId.text()
            barkode = self.edtBarkode.text()
            name = self.edtName.text()
            kategori = self.edtKategori.text()
            qty = self.edtQty.text()
            harga = self.edtHarga.text()

            if not all([Id, barkode, name, kategori, qty, harga]):
                QMessageBox.warning(None, "Error", "Pastikan semua field diisi!")
                return

            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_penjualan"
            )
            cursor = mydb.cursor()
            sql = "UPDATE product SET barkode = %s, name = %s, kategori = %s, qty = %s, harga = %s WHERE Id = %s"
            val = (barkode, name, kategori, qty, harga, Id)
            cursor.execute(sql, val)
            mydb.commit()
            self.loadproduct()
        except mc.Error as e:
            QMessageBox.critical(None, "Error", f"Database error: {str(e)}")

    def hapusproduct(self):
        try:
            Id = self.edtId.text()
            if not Id:
                QMessageBox.warning(None, "Error", "Field ID tidak boleh kosong!")
                return

            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_penjualan"
            )
            cursor = mydb.cursor()
            sql = "DELETE FROM product WHERE Id = %s"
            val = (Id,)
            cursor.execute(sql, val)
            mydb.commit()

            if cursor.rowcount > 0:
                QMessageBox.information(None, "Success", "Data berhasil dihapus!")
            else:
                QMessageBox.warning(None, "Warning", "Data tidak ditemukan!")

            self.loadproduct()
            self.edtId.clear()
        except mc.Error as e:
            QMessageBox.critical(None, "Error", f"Database error: {str(e)}")

    def cariproduct(self):
        try:
            Id = self.edtCari.text()
            if not Id:
                QMessageBox.warning(None, "Error", "Field Cari tidak boleh kosong!")
                return

            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_penjualan"
            )
            cursor = mydb.cursor()
            sql = "SELECT * FROM product WHERE Id = %s"
            val = (Id,)
            cursor.execute(sql, val)
            result = cursor.fetchone()

            if result:
                self.edtId.setText(str(result[0]))
                self.edtBarkode.setText(result[1])
                self.edtName.setText(result[2])
                self.edtKategori.setText(result[3])
                self.edtQty.setText(str(result[4]))
                self.edtHarga.setText(str(result[5]))
            else:
                QMessageBox.warning(None, "Warning", "Data tidak ditemukan!")
        except mc.Error as e:
            QMessageBox.critical(None, "Error", f"Database error: {str(e)}")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "NAMA : MUHAMMAD RENALDI"))
        self.label_2.setText(_translate("Form", "ID"))
        self.label_3.setText(_translate("Form", "BARKODE"))
        self.label_4.setText(_translate("Form", "NAME"))
        self.label_5.setText(_translate("Form", "KATEGORI"))
        self.label_6.setText(_translate("Form", "QTY"))
        self.label_7.setText(_translate("Form", "HARGA"))
        self.label_8.setText(_translate("Form", "NPM : 2210010116"))
        self.label_9.setText(_translate("Form", "KELAS : 5P REG BANJARMASIN"))
        self.label_10.setText(_translate("Form", "UJIAN AKHIR SEMESTER"))
        self.tSimpan.setText(_translate("Form", "SIMPAN"))
        self.tUbah.setText(_translate("Form", "UBAH"))
        self.tHapus.setText(_translate("Form", "HAPUS"))
        self.tCari.setText(_translate("Form", "CARI"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "BARKODE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "NAME"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "KATEGORI"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "QTY"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "HARGA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())